### ISSUE TITLE
Repo name change.

### ISSUE THREAD

**Issue by ablaom** [JuliaAI/ScientificTypes.jl#125]
Given the disruption and limited resources, I'm not overly enthusiastic about a name change. However, this has been raised elsewhere I'm opening an issue to track and invite any comment.

1. One proposal is to make these repo name changes: **edit** ✔️ proceeding

ScientificTypes -> ScientificTypesBase
MLJScientificTypes -> ScientificTypes

Some context: https://github.com/JuliaData/Tables.jl/issues/240 https://github.com/JuliaData/Tables.jl/issues/190

According to current General.jl, the effected active repos would be: 

./S/StatisticalTraits/Deps.toml:2:ScientificTypes = "321657f4-b219-11e9-178b-2701a2544e81"
./M/MLJModels/Deps.toml:15:MLJScientificTypes = "2e2323e0-db8b-457b-ae0d-bdfb3bc63afd"
./M/MLJModels/Deps.toml:24:ScientificTypes = "321657f4-b219-11e9-178b-2701a2544e81"
./M/MLJBase/Deps.toml:27:MLJScientificTypes = "2e2323e0-db8b-457b-ae0d-bdfb3bc63afd"
./M/MLJBase/Deps.toml:52:ScientificTypes = "321657f4-b219-11e9-178b-2701a2544e81"
./M/MLJScientificTypes/Deps.toml:5:ScientificTypes = "321657f4-b219-11e9-178b-2701a2544e81"
./M/MLJModelInterface/Deps.toml:2:ScientificTypes = "321657f4-b219-11e9-178b-2701a2544e81"
./M/MLJ/Deps.toml:44:ScientificTypes = "321657f4-b219-11e9-178b-2701a2544e81"
./M/MLJFlux/Deps.toml:12:ScientificTypes = "321657f4-b219-11e9-178b-2701a2544e81"

2. ~~A substantially less disruptive proposal is to just rename MLJScientificTypes to something like ScientificTypesConvention (ugh! 🤮 ) or ??~~

**Comment by ablaom** [comment]
cc  @juliohm

**Comment by tlienart** [comment]
Your proposal 1 seems fine to me. The only thing is to clarify in the readme that in a way it carries an "opinion" on how data can be interpreted by default and that users could define their own convention (I think this is already there).

That said, I think it makes sense to remove 'MLJ' from the name because what is done in there is fairly natural (I think).

**Comment by juliohm** [comment]
It would be great to see this useful work on scientific types more widely spread in the Julia ecosystem, and proposal (1) with a project-agnostic name is a great proposal. As I commented in the other issue, another thing to consider is if scientific types could leave in a community-driven organization such as JuliaData. As an ex-employer of IBM, I have no write access to repositories I used to work on that are hosted in the IBM GitHub organization. If something like this happens to a foundational package like ScientificTypes.jl that would be unfortunate. This is a secondary issue, the most important issue we need to address is spreading the scientific types across many more packages in the data science stack.

**Comment by juliohm** [comment]
Is there anything I can do to help with this migration? I am looking forward to use scientific types in more packages downstream.

**Comment by ablaom** [comment]
@juliohm Thanks for the offer of help. 

Note that the two repos in question have now been transferred to JuliaAI, and the urls updated at General.jl. I'm assuming now that Option 1 [above](https://github.com/JuliaAI/ScientificTypes.jl/issues/125#issue-909967441) is how we will proceed.

@DilumAluthge's [suggestion](https://github.com/JuliaRegistries/General/pull/38775#issuecomment-860290608) for proceeding is copied below:

- [ ] 1. Create a new package and call it ScientificTypesBase.

- [ ] 2. Copy all of the content of ScientificTypes into ScientificTypesBase. Now register ScientificTypesBase as a new package.

- [ ] 3. Now, delete all contents of the ScientificTypes package and replace them with the contents of the MLJScientificTypes package. Then make a new breaking release of ScientificTypes.

- [ ] 4. Now you can deprecate the MLJScientificTypes package.

Then there will be a lot work updating stuff downstream. I'll start with the first two items today and then maybe @juliohm, you take over some of the rest after ScientificTypesBase is registered?

**Comment by ablaom** [comment]
Step 1 done, subject to merge at General: https://github.com/JuliaRegistries/General/pull/38778

**Comment by juliohm** [comment]
Thank you @ablaom , I will help with the missing steps 3 and 4 after the new package is merged 👍🏽

**Comment by ablaom** [comment]
@juliohm If you have time, can you prepare the PR for step 3? ScientificTypesBase 1.0.0 is now released.

**Comment by ablaom** [comment]
There is still lots of work needed to roll these changes out in the MLJ ecosystem (and GeoStats). I will open a new issue for the MLJ side.

@juliohm
