### ISSUE TITLE
Schema should redirect output to the REPL

### ISSUE THREAD

**Issue by tlienart** [JuliaAI/ScientificTypes.jl#129]
I'm not sure how to do  it but it should be easy to do:  when evaluating `schema(df)` in Juno, the output is shown "inlined" 

![Screen Shot 2020-05-24 at 16 12 14](https://user-images.githubusercontent.com/10897531/82756247-5b183a80-9dd9-11ea-8f01-5aa4062a53cb.png)

it should be shown in the REPL instead.

**Comment by ablaom** [comment]
@OkonSamuel This is an ancient issue and Juno is now supplanted by VS Code. I think you use this, no? Do you have an issue with the display of schema there?

**Comment by OkonSamuel** [comment]
I'll check if this is also an issue with Vs Code.

**Comment by OkonSamuel** [comment]
I can confirm that on Vscode the output of schema is redirected to the REPL.
