### ISSUE TITLE
Accept strings in `coerce`

### ISSUE THREAD

**Issue by juliohm** [JuliaAI/ScientificTypes.jl#161]
Currently `coerce(table, "col name" => Continuous)` fails. I had to wrap the column name as `Symbol("col name")` for it to work.

**Comment by ablaom** [comment]
Thanks. Just to clarify, you are requesting this a feature, not reporting what you think may be a bug?

**Comment by juliohm** [comment]
As a feature :)

**Comment by ablaom** [comment]
Sounds reasonable to me. PR welcome :-)
